
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - flux-net

  api:
    build: .
    command: python api.py
    ports:
      - "5000:5000"
    depends_on:
      - redis
    # Inject secrets from .env file
    env_file:
      - .env
    networks:
      - flux-net

  worker:
    build: .
    command: ["python", "worker.py"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_DEFAULT_REGION=ap-south-1
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE}
    depends_on:
      - redis
    env_file:
      - .env
    deploy:
      replicas: 3
    networks:
      - flux-net

networks:
  flux-net:
    driver: bridge