
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - flux-net

  api:
    build: .
    command: python api.py
    ports:
      - "5000:5000"
    depends_on:
      - redis
    # Inject secrets from .env file
    env_file:
      - .env
    networks:
      - flux-net

  worker:
    build: .
    command: python worker.py
    depends_on:
      - redis
    #  Inject secrets from .env file
    env_file:
      - .env
    deploy:
      replicas: 3
    networks:
      - flux-net

networks:
  flux-net:
    driver: bridge